# ============================================================================
# BANNER REPOSITORY
# ============================================================================
# This file was auto-generated on: 2026-02-23 22:11:11 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.banner import BannerUpdate, BannerCreate, BannerOut

async def create_banner(banner_data: BannerCreate) -> BannerOut:
    banner_dict = banner_data.model_dump()
    result =await db.banners.insert_one(banner_dict)
    result = await db.banners.find_one(filter={"_id":result.inserted_id})
    returnable_result = BannerOut(**result)
    return returnable_result

async def get_banner(filter_dict: dict) -> Optional[BannerOut]:
    try:
        result = await db.banners.find_one(filter_dict)

        if result is None:
            return None

        return BannerOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching banner: {str(e)}"
        )
    
async def get_banners(filter_dict: dict | None = None,start: int = 0,stop: int = 100) -> List[BannerOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.banners.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        banner_list = []

        async for doc in cursor:
            banner_list.append(BannerOut(**doc))

        return banner_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching banners: {str(e)}"
        )
async def update_banner(filter_dict: dict, banner_data: BannerUpdate) -> BannerOut | None:
    result = await db.banners.find_one_and_update(
        filter_dict,
        {"$set": banner_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    if result is None:
        return None
    return BannerOut(**result)

async def delete_banner(filter_dict: dict):
    return await db.banners.delete_one(filter_dict)