# ============================================================================
# NOTIFICATIONS REPOSITORY
# ============================================================================
# This file was auto-generated on: 2026-03-06 08:56:36 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.notifications import NotificationsUpdate, NotificationsCreate, NotificationsOut

async def create_notifications(notifications_data: NotificationsCreate) -> NotificationsOut:
    notifications_dict = notifications_data.model_dump()
    result =await db.notificationss.insert_one(notifications_dict)
    result = await db.notificationss.find_one(filter={"_id":result.inserted_id})
    returnable_result = NotificationsOut(**result)
    return returnable_result

async def get_notifications(filter_dict: dict) -> Optional[NotificationsOut]:
    try:
        result = await db.notificationss.find_one(filter_dict)

        if result is None:
            return None

        return NotificationsOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching notifications: {str(e)}"
        )
    
async def get_notificationss(filter_dict: dict | None = None,start: int = 0,stop: int = 100) -> List[NotificationsOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.notificationss.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        notifications_list = []

        async for doc in cursor:
            notifications_list.append(NotificationsOut(**doc))

        return notifications_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching notificationss: {str(e)}"
        )
async def update_notifications(filter_dict: dict, notifications_data: NotificationsUpdate) -> NotificationsOut | None:
    result = await db.notificationss.find_one_and_update(
        filter_dict,
        {"$set": notifications_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    if result is None:
        return None
    return NotificationsOut(**result)

async def delete_notifications(filter_dict: dict):
    return await db.notificationss.delete_one(filter_dict)